Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'CodeQ.GuidedTour:JQuery':
            resource: resource://CodeQ.GuidedTour/Public/jquery.min.js
          'CodeQ.GuidedTour:EnjoyHint':
            resource: resource://CodeQ.GuidedTour/Public/enjoyhint.min.js
          'CodeQ.GuidedTour:Plugin':
            resource: resource://CodeQ.GuidedTour/Public/Plugin.js
        stylesheets:
          'CodeQ.GuidedTour:EnjoyHint':
            resource: resource://CodeQ.GuidedTour/Public/enjoyhint.css